config/routes.rb
Rails.application.routes.draw do
  get 'contacts/new'
  devise_for :users

  root to: 'pages#home'

  resources :shows, only: [:show, :index] do
    member do
      get 'follow'
      get 'unfollow'
    end
  end

  resources :performances, only: [:index] do
    resources :planners, only: [:create]
  end

  get 'shortlist', to: 'pages#shortlist'
  resources :shortlist, only: [:show]

  get 'planner', to: 'pages#planner'

  get 'planners', to: 'planners#index'
  delete 'planners/:id', to: 'planners#destroy', as: :delete_planner

  get 'contacts', to: 'contacts#new'
  resources :contacts, only: [:new, :create]

  get 'about', to: 'pages#about'
end

app/views/shared/_colorchart.html.erb
<div class="color-chart">
  <%= link_to "COMEDY" , shows_path(category: "Comedy"), class: "color-chart-label color-comedy" %>
  <%= link_to "CABARET & VARIETY" , shows_path(category: "Cabaret and Variety" ), class: "color-chart-label color-cabaret-variety" %>
  <%= link_to "CIRCUS & PHYSICAL THEATRE" , shows_path(category: "Dance Physical Theatre and Circus" ), class: "color-chart-label color-circus-etc" %>
  <%= link_to "THEATRE, MUSICALS & OPERA" , shows_path(category: "Musicals and Opera"), class: "color-chart-label color-theatre-etc" %>
  <%= link_to "EVENTS & EXHIBITIONS" , shows_path(category: "Events"), class: "color-chart-label color-events-etc" %>
  <%= link_to "OTHER" , shows_path(category: "Children's Shows"), class: "color-chart-label color-other" %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="footer-signature">
    <%= link_to "My Fringe Planner", root_path %>
  </div>

  <div class="footer-social-icons">
    <span><a href="https://www.facebook.com/edfringe/" target="_blank"><i class="fab fa-facebook-square"></i></i></a></span>
    <span><a href="https://www.instagram.com/edfringe/?hl=en" target="_blank"><i class="fab fa-instagram"></i></a></span>
    <span><a href="https://twitter.com/edfringe?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor" target="_blank"><i class="fab fa-twitter-square"></i></a></span>
  </div>

  <div>
    <%= link_to "Contact Us", contacts_new_path, class: "footer-links" %>
    <%= link_to "About", about_path, class: "footer-links" %>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="background-blue navbar-expand-sm navbar-light navbar-lewagon navbar-powerful">
  <%= link_to root_path do %>
    <%= image_tag "my-fringe-planner-logo.png", class: 'logo'%>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div>
    <div class="top">
      <%= link_to "SHOWS", shows_path, class: "big-nav-link" %>
      <%= link_to "SHORTLIST", shortlist_path, class: "big-nav-link" %>
      <%= link_to "PLANNER", planner_path, class: "big-nav-link" %>
      <div class="greeting">
        <%if current_user%>
          <p>Hi, <%= current_user.first_name %></p>
        <% end %>
      </div>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
        <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown">
      <i class="fas fa-bars" id="navbarDropdown" data-toggle="dropdown"></i>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%if current_user%>
            <%= link_to "My Fringe", planners_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          <% else %>
            <%= link_to "Log in", new_user_session_path, class: "dropdown-item" %>
            <%= link_to "Sign up", new_user_registration_path, class: "dropdown-item" %>
          <% end %>
        </div>
      </li>
      </div>
    </div>
    <div class="filter-wrapper">
      <% @collection = [] %>
      <% ("#{Time.now.year}/08/01".to_date.."#{Time.now.year}/08/31".to_date).each do |date| %>
        <% @collection << date.strftime("%A %e %B") %>
      <% end %>
      <%= simple_form_for :filter, url: shows_path, method: :get, class: "form-search d-flex", id: "form-styling" do |f| %>
        <%= f.input :show, label: false, placeholder: "Show/Performer", input_html: {class: 'search-show-input' } %>
        <%= f.input :genre, label: false, collection: Show::GENRES, prompt: "Category", input_html: {class: 'genre-style' } %>
        <%= f.input :start_date, as: :select, collection: @collection, label: false, prompt: "From Date", class: 'search-start-date' %>
        <%= f.input :end_date, as: :select, collection: @collection, label: false, prompt: "To Date", input_html: { class: 'search-end-date' } %>
        <%= f.submit value: "Search", class: "submit", data: {disable_with: 'Search'} %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_show.html.erb
<div class="card">
  <div class="card-star-n-image">
    <% if current_user&.following?(show) %>
      <%= link_to unfollow_show_path(show) do  %>
        <i class="fa fa-star star-yellow" aria-hidden="true"></i>
      <% end %>
    <% else %>
      <%= link_to follow_show_path(show) do  %>
        <i class="fa fa-star star-white" aria-hidden="true"></i>
      <% end %>
    <% end %>
    <%= image_tag(show.original_image, :alt => "#{show.artist}") %>
  </div>
  <div class="card-info card-border <%= show.colour_class %>">
    <h6><%= truncate(show.title, length: 75) %></h6>
    <p><%= show.genre %></p>
    <div class="d-flex">
      <p><i class="fas fa-clock fa-fw" aria-hidden="true"></i> <%= truncate(show.starts, length: 10) %> (<%= show.duration %>) </p>
      <p><i class="fa fa-calendar fa-fw card-dates" aria-hidden="true"></i> <%= truncate(show.dates_string, length: 30) %></p>
    </div>
    <div class="d-flex justify-content-between">
      <p><i class="fas fa-map-marker-alt fa-fw"></i> <%= truncate(show.venue.name, length: 45) %></p>
      <p>£<%= show.performances.last.price %></p>
    </div>
  </div>
  <%= link_to show_path(show) do %>
    <div class="hid-link"></div>
  <% end %>
</div>