config/routes.rb
Rails.application.routes.draw do
  get 'contacts/new'
  devise_for :users

  root to: 'pages#home'

  resources :shows, only: [:show, :index] do
    member do
      get 'follow'
      get 'unfollow'
    end
  end

  resources :performances, only: [:index] do
    resources :planners, only: [:create]
  end

  get 'shortlist', to: 'pages#shortlist'
  resources :shortlist, only: [:show]

  get 'planner', to: 'pages#planner'

  get 'planners', to: 'planners#index'
  delete 'planners/:id', to: 'planners#destroy', as: :delete_planner

  get 'contacts', to: 'contacts#new'
  resources :contacts, only: [:new, :create]

  get 'about', to: 'pages#about'
end

app/views/pages/_planner.html.erb
<div class="plan planner-card <%= planner.planner_clash(@planners, planner) %>">
  <div class="planner-card-show-image">
    <% if @hand %>
      <%= image_tag(planner.performance.show.original_image, :alt => "#{planner.performance.show.artist}", height: planner.duration.to_f/100*2440) %>
      <%= image_tag "arrow-right.png", class: "card-arrow" %>
    <% else %>
      <%= image_tag(planner.performance.show.original_image, :alt => "#{planner.performance.show.artist}") %>
      <div title="Add to Calendar" class="addeventatc">
        <span class="start"><%= planner.date %></span>
        <span class="end"><%= planner.performance.end %></span>
        <span class="timezone">United Kingdom</span>
        <span class="title"><%= planner.performance.show.title %></span>
        <span class="description"><%= planner.performance.show.description %></span>
        <span class="location"><%= planner.performance.show.venue.name %>, <%= planner.performance.show.venue.address %>, <%= planner.performance.show.venue.postcode %></span>
      </div>
    <% end %>
  </div>
  <div class="planner-card-info card-border <%= planner.performance.show.colour_class %> ">
    <h6><%= truncate(planner.performance.show.title, length: 40) %></h6>
    <div>
      <p><%= planner.performance.show.genre %></p>
      <div class="d-flex">
        <p><i class="fas fa-clock fa-fw" aria-hidden="true"></i> <%= planner.performance.time %></p>
      </div>
      <div class="d-flex justify-content-between">
        <p><i class="fas fa-map-marker-alt fa-fw"></i> <%= truncate(planner.performance.show.venue.name, length: 35) %></p>
        <p>£<%= planner.performance.price %></p>
      </div>
    </div>
  </div>
</div>

app/views/pages/_planner_info_window.html.erb
<%= link_to "https://www.google.com/maps/search/#{booking.performance.show.venue.postcode}", target: :blank, class: "gmaps-link" do %>
  <h6><%= booking.performance.show.title %></h6>
  <p><%= booking.performance.start.strftime("%H:%M") %> - <%= booking.performance.end.strftime("%H:%M") %></p>
  <p><%= booking.performance.show.venue.space %></p>
  <p><%= booking.performance.show.venue.name %></p>
  <p><%= booking.performance.show.venue.postcode %></p>
<% end %>

app/views/pages/_planner_shortlist.html.erb
<div class="card <%= performance.shortlist_clash(@planners, performance) %>">
  <div class="card-star-n-image">
    <% if current_user&.following?(performance.show) %>
      <%= link_to unfollow_show_path(performance.show) do  %>
        <i class="fa fa-star star-yellow" aria-hidden="true"></i>
      <% end %>
    <% else %>
      <%= link_to follow_show_path(performance.show) do  %>
        <i class="fa fa-star star-white" aria-hidden="true"></i>
      <% end %>
    <% end %>
    <%= image_tag(performance.show.original_image, class: "card-show-image", :alt => "performance.show.artist") %>
    <%= image_tag "arrow-left.png", class: "card-arrow" %>
  </div>
  <div class="card-info card-border <%= performance.show.colour_class %>">
    <h6><%= truncate(performance.show.title, length: 70) %></h6>
    <p><%= performance.show.genre %></p>
    <div class="d-flex">
      <p><i class="fas fa-clock fa-fw" aria-hidden="true"></i> <%= truncate(performance.time, length: 15) %></p>
      <p><i class="fa fa-calendar fa-fw card-dates" aria-hidden="true"></i> <%= truncate(performance.show.dates_string, length: 35) %></p>
    </div>
    <div class="d-flex justify-content-between">
      <p><i class="fas fa-map-marker-alt fa-fw"></i> <%= truncate(performance.show.venue.name, length: 40) %></p>
      <p>£<%= performance.show.performances.last.price %></p>
    </div>
  </div>

  <%= link_to performance_planners_path(performance ,@planner, day: params[:day]), class: "planner-in-link", method: :post do  %>
    <div class="hid-link"></div>
  <% end %>
</div>

app/views/pages/_walk_time.html.erb
<% if @planners[index + 1] != nil %>
  <% journey_info =  planner.calc_distance(@planners, index) %>
  <% if @planners[index + 1].performance.start < planner.walk_end(journey_info) %>
    <div class="planner-card walk-notif walk-red" style=" height: <%= planner.walk_duration(journey_info) %>; width: 100%">
  <% else %>
    <div class="planner-card walk-notif" style=" height: <%= planner.walk_duration(journey_info) %>; width: 100%">
  <% end %>
    <p><i class="fas fa-walking fa-fw"></i><%= (journey_info["routes"].first["duration"] / 60).ceil %> minute walk to <%= @planners[ index + 1 ].performance.show.venue.name %></p>
  </div>
<% end %>

app/views/pages/about.html.erb
<div class="body-container">
  <h1 class="about-title">About MyFringePlanner</h1>
  <div class="d-flex justify-content-between">
    <div>
      <h2>The Story</h2>
      <hr></hr>

      <div class="about-story">
        <div class="about-story-story">
          <p>Every August, Edinburgh plays host to the magnificent <%= link_to "Fringe", "https://tickets.edfringe.com/" %>, the world’s largest arts and culture festival and most ticketed event after the Olympic Games! 1000s of shows are performed around the clock, ranging from comedy to cabaret, circus, theatre, dance and more!</p>
          <p>You are thoroughly spoilt for choice but the flip side is the Herculean effort that goes into planning your festival. Fringe-goers are known to painstakingly construct monstrous, heavily formatted spreadsheets that scroll for miles with dozens of shortlisted shows and puzzle-pieced schedules!</p>
          <p>Admittedly I actually love a spreadsheet but all that manual, error-prone work isn’t ideal so when Pitch Day came round for products to invent, design, code and launch as a final, 2 week project at <%= link_to "Le Wagon", "https://www.lewagon.com/london" %>, (the #1 ranked coding bootcamp on Switchup and Coursereport), the myfringeplanner web app was born!</p>
          <p>Like most Fringe shows, <%= link_to "myfringeplanner", "https://www.myfringeplanner.com/" %> is still a WIP, but we'll be fully live with even more features soon...</p>
        </div>
        <div>
          <%= image_tag "about-pain-pic.png", alt: "image of messy graph", class: "about-story-pic" %>
        </div>
      </div>
    </div>
  </div>

  <br>

  <h2>The Team</h2>
  <hr></hr>

  <div class="about-profile">
    <%= image_tag "https://avatars0.githubusercontent.com/u/56324000?v=4", alt: "Dee Lye" %>
    <div>
      <h4>Dee Lye</h4>
      <p>I'm an ex-investment banker extending my slightly sadistic enjoyment of the puzzle-solving nature of programming by beginning a new career as a full-stack developer with the ultimate dream of being able to work freelance from home or somewhere with a bring-your-dog-to-work policy!</p>
    </div>
  </div>
  <div class="about-profile">
    <%= image_tag "https://res.cloudinary.com/wagon/image/upload/c_fill,g_face,h_200,w_200/v1582206247/s37cq5fva5b7ymbjd7xv.jpg", alt: "Jessica DeWitt" %>
    <div>
      <h4>Jessica DeWitt</h4>
      <p>I'm a recent college grad who worked as a freelance Content Creator. I want to learn code so that I can implement what I write and learn how to do front end development. After the program, I hope to get a job as a junior developer in Norway.</p>
    </div>
  </div>
  <div class="about-profile">
    <%= image_tag "https://avatars1.githubusercontent.com/u/50817798?v=4", alt: "Agisilaos Karkalos" %>
    <div>
      <h4>Agisilaos Karkalos</h4>
      <p>Hi My name is Agis, I am originally from Greece and moved here a few years ago. I have worked since in the hospitality industry and felt like it was time to change my career and give myself another challenge. I am looking forward to learn and meet some new people in the process! ghf!</p>
    </div>
  </div>
  <div class="about-profile">
    <%= image_tag "https://avatars3.githubusercontent.com/u/57145417?v=4", alt: "Jahaira" %>
    <div>
      <h4>Jahaira Castaneda</h4>
      <p>I have four years experience working in the mental health field as a therapist. I find coding to be very creative and have always been fascinated with how websites and applications are built. Looking forward to starting a new career that will challenge and allow me to find new opportunities in the tech industry.</p>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="home-page home-page-w-img" >
  <div class="home-nav">
    <%= image_tag "my-fringe-planner-logo.png", alt: "myfringeplanner logo"%>
    <div>
      <%= link_to "Sign up", new_user_registration_path, class: "home-btn-sign-up" %>
      <%= link_to "Log in", new_user_session_path, class: "button log-in-btn" %>
    </div>
  </div>
  <div class="home-title">
    <h1>Plan your
    <%= link_to "Edinburgh Fringe Festival", "https://www.edfringe.com/", class:"home-special-font", target: "_blank" %>
    in minutes...</h1>
    <!-- <h1>Plan your <span class="home-special-font">Edinburgh Fringe Festival</span> in minutes...</h1> -->
  </div>
  <div class="filter-wrapper">
    <% @collection = [] %>
    <% ("2020/08/01".to_date.."2020/08/31".to_date).each do |date| %>
      <% @collection << date.strftime("%A %e %B") %>
    <% end %>
    <%= simple_form_for :filter, url: shows_path, method: :get, class: "form-search d-flex", id: "form-styling" do |f| %>
      <%= f.input :show, label: false, placeholder: "Show/Performer", input_html: {class: 'search-show-input' } %>
      <%= f.input :genre, label: false, collection: Show::GENRES, prompt: "Category", input_html: {class: 'genre-style' } %>
      <%= f.input :start_date, as: :select, collection: @collection, label: false, prompt: "From Date", class: 'search-start-date' %>
      <%= f.input :end_date, as: :select, collection: @collection, label: false, prompt: "To Date", input_html: { class: 'search-end-date' } %>
      <%= f.submit value: "Search", class: "submit", data: {disable_with: 'Search'} %>
    <% end %>
  </div>
  <div class="arrow">
    <svg class="more-arrows">
      <polygon class="arrow-top" points="37.6,27.9 1.8,1.3 3.3,0 37.6,25.3 71.9,0 73.7,1.3 "/>
      <polygon class="arrow-middle" points="37.6,45.8 0.8,18.7 4.4,16.4 37.6,41.2 71.2,16.4 74.5,18.7 "/>
      <polygon class="arrow-bottom" points="37.6,64 0,36.1 5.1,32.8 37.6,56.8 70.4,32.8 75.5,36.1 "/>
    </svg>
  </div>
</div>
<div class="home-page home-work-div">
  <h1>How does it <span class="home-special-font">work</span>?</h1>
  <div class="home-cards">
    <div class="home-card">
      <div class="d-flex">
        <h3 class=home-num>1</h3>
        <h3>Search for shows</h3>
      </div>
      <p>Quickly find shows by name or the dates you're attending the Fringe; all the listings can be found here!</p>
    </div>
    <div class="home-card">
      <div class="d-flex">
        <h3 class="home-num">2</h3>
        <h3>Create a shortlist</h3>
      </div>
      <p>Easily make, access and edit your readily available shortlist with shows from your search results.</p>
    </div>
    <div class="home-card">
      <div class="d-flex">
        <h3 class="home-num">3</h3>
        <h3>Build a planner</h3>
      </div>
      <p>Effortlessly add shows to your planner, which populates walk times between venues and helps you spot gaps and clashes during the day.</p>
    </div>
  </div>
</div>

app/views/pages/planner.html.erb
<div class="body-container">
  <div class="planner-search-bar">
    <form id="date-form" hidden>
      <input class="cal-date" name="day" type="text" value="">
      <button class="button planner-btn" type=>Plan</button>
    </form>
  </div>

  <br>

  <div><h3 class="cal-grid-title">AUGUST <%= Time.now.year %></h3></div>
  <div class="cal-grid-days">
    <p>F</p>
    <p>S</p>
    <p>S</p>
    <p>M</p>
    <p>T</p>
    <p>W</p>
    <p>T</p>
    <p>F</p>
    <p>S</p>
    <p>S</p>
    <p>M</p>
    <p>T</p>
    <p>W</p>
    <p>T</p>
    <p>F</p>
    <p>S</p>
    <p>S</p>
    <p>M</p>
    <p>T</p>
    <p>W</p>
    <p>T</p>
    <p>F</p>
    <p>S</p>
    <p>S</p>
    <p>M</p>
  </div>
  <div class="cal-grid-dates">
    <button class="cal-grid-date" data-day="day=7" style="border-radius: 0px 0px 0px 5px">7</button>
    <button class="cal-grid-date" data-day="day=8">8</button>
    <button class="cal-grid-date" data-day="day=9">9</button>
    <button class="cal-grid-date" data-day="day=10">10</button>
    <button class="cal-grid-date" data-day="day=11">11</button>
    <button class="cal-grid-date" data-day="day=12">12</button>
    <button class="cal-grid-date" data-day="day=13">13</button>
    <button class="cal-grid-date" data-day="day=14">14</button>
    <button class="cal-grid-date" data-day="day=15">15</button>
    <button class="cal-grid-date" data-day="day=16">16</button>
    <button class="cal-grid-date" data-day="day=17">17</button>
    <button class="cal-grid-date" data-day="day=18">18</button>
    <button class="cal-grid-date" data-day="day=19">19</button>
    <button class="cal-grid-date" data-day="day=20">20</button>
    <button class="cal-grid-date" data-day="day=21">21</button>
    <button class="cal-grid-date" data-day="day=22">22</button>
    <button class="cal-grid-date" data-day="day=23">23</button>
    <button class="cal-grid-date" data-day="day=24">24</button>
    <button class="cal-grid-date" data-day="day=25">25</button>
    <button class="cal-grid-date" data-day="day=26">26</button>
    <button class="cal-grid-date" data-day="day=27">27</button>
    <button class="cal-grid-date" data-day="day=28">28</button>
    <button class="cal-grid-date" data-day="day=29">29</button>
    <button class="cal-grid-date" data-day="day=30">30</button>
    <button class="cal-grid-date" data-day="day=31" style="border-radius: 0px 0px 5px 0px">31</button>
  </div>

  <div class="planner-container">
    <div>
      <h1 class="planner-header">
        MY FRINGE
        <%= link_to planners_path do  %>
          <i class="fa fa-calendar-plus planner-add-cal" aria-hidden="true"></i>
        <% end %>
      </h1>
      <% if @planners != [] %>
        <p style="width: 350px">Click a planned show to remove it from the planner or the export icon above to add to your own calendar.</p>
      <% end %>
      <div class="my-shadow">
        <div class="planner-date"><h3><%= @dayname %></h3></div>
        <div class="planner-day">
          <div class="planner">
            <div class="planner-times">
              <p>06:00</p>
              <p>07:00</p>
              <p>08:00</p>
              <p>09:00</p>
              <p>10:00</p>
              <p>11:00</p>
              <p>12:00</p>
              <p>13:00</p>
              <p>14:00</p>
              <p>15:00</p>
              <p>16:00</p>
              <p>17:00</p>
              <p>18:00</p>
              <p>19:00</p>
              <p>20:00</p>
              <p>21:00</p>
              <p>22:00</p>
              <p>23:00</p>
              <p>00:00</p>
              <p>01:00</p>
              <p>02:00</p>
              <p>03:00</p>
              <p>04:00</p>
              <p>05:00</p>
            </div>
            <div class="day-calendar">
              <% if @planners != false %>
                <% @planners.delete_if{ |planner| planner == false } %>
                <% @planners.sort_by! { |planner| planner.performance.start } %>
                <% @planners.each_with_index do |planner, index| %>
                  <%= link_to delete_planner_path(id: planner.id, day: params[:day]), method: :delete do  %>
                    <div class="plan" style="top: <%= planner.top %>; height: <%= planner.duration %>; width: 100%">
                      <%= render "planner", planner: planner %>
                    </div>
                    <div class="walk-transition" style="top: <%= (planner.top.to_f + planner.duration.to_f).to_s + '%' %>;">
                      <%= render "walk_time", planner: planner, index: index %>
                    </div>
                  <% end %>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
        <div class="planner-footer"></div>
      </div>
    </div>

    <div class="planner-shortlist">
      <h1 class="planner-header">
        SHORTLIST
        <%= link_to shortlist_path do  %>
          <i class="fas fa-list planner-add-cal" aria-hidden="true"></i>
        <% end %>
      </h1>
      <div>
        <% if !params[:day].present? %>
          <p>Choose a date to start planning!</p>
        <% elsif @performances == [] || @shortlist == [] %>
          <p>Check out the <%= link_to "listings", shows_path, class: "planners-shows-link" %> to find shows for your shortlist!</p>
        <% else %>
          <p>Click a shortlisted show to add it to the planner but careful of performance clashes and insufficient walking times between venues, which will be highlighted in red.</p>
          <div class="planner-cards">
            <% @performances.each do |performance| %>
              <%= render 'pages/planner_shortlist', performance: performance %>
            <% end %>
          </div>
        <% end %>

        <% if @planners != [] %>
          <h1 class="planner-header">PLANNED VENUES</h1>
          <p>Click a marker for show and venue information.</p>
          <div id="planner-map"
            class="planner-map"
            style="width: 100%; height: 300px;"
            data-markers="<%= @markers.to_json %>"
            data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">

  // prevents page rendering at the top on reload
  if (localStorage['scroll']) {
    window.scroll({ top: localStorage['scroll'] })
  }
  window.addEventListener('scroll', () => {
    localStorage['scroll'] = window.scrollY;
  });

  // prevents page scrolling when planner scrolling goes beyond its top/bottom limits
  var scrollable = document.querySelector(".planner-day");
  scrollable.addEventListener('wheel', function(event) {
    var deltaY = event.deltaY;
    var contentHeight = scrollable.scrollHeight;
    var visibleHeight = scrollable.offsetHeight;
    var scrollTop = scrollable.scrollTop;

    if (scrollTop === 0 && deltaY < 0)
      event.preventDefault();
    else if (visibleHeight + scrollTop === contentHeight && deltaY > 0)
      event.preventDefault();
  });

  // reloads planner in same spot upon webpage refresh
  scrollable.addEventListener('scroll',function() {
    localStorage.setItem('scrollPosition',scrollable.scrollTop);
  },false);

  window.addEventListener('load',function() {
    if(localStorage.getItem('scrollPosition') !== null)
      $("div.planner-day").scrollTop(localStorage.getItem('scrollPosition'));
  },false);
</script>

app/views/pages/shortlist.html.erb
<div class="body-container">
  <%= render 'shared/colorchart' %>

  <% if @follows == [] %>
    <p class="shortlist-empty-message">Check out the <%= link_to "listings", shows_path, class: "planners-shows-link" %> to find shows for your shortlist!</p>
  <% end %>

  <div class="cards">
    <% @follows = @follows.sort_by { |follow| follow.followable.title.capitalize } %>
    <% @follows.each do |follow| %>
      <% show = follow.followable %>
      <%= render 'shared/show', show: show %>
    <% end %>
  </div>
</div>

<!-- prevents page rendering at the top on reload -->
<script>
  if (localStorage['scroll']) {
    window.scroll({ top: localStorage['scroll'] })
  }
  window.addEventListener('scroll', () => {
    localStorage['scroll'] = window.scrollY;
  });
</script>